-- Persistent, versioned Route Campaign profiles and progress.
--
-- Files are data-only Lua tables generated by this module. They are loaded in
-- an empty environment and validated before use. Runtime data lives under
-- user_data/, which is intentionally ignored by Git.

local M = {}

local script_path = debug.getinfo(1, "S").source:sub(2)
local script_dir = script_path:match("(.*[/\\])") or "./"
local base_dir = script_dir .. "../user_data/"

local SCHEMA_VERSION = 1
local INDEX_FILE = "campaign_index.lua"

local function file_exists(path)
    local f = io.open(path, "r")
    if f == nil then return false end
    f:close()
    return true
end

local function sorted_keys(value)
    local keys = {}
    for key in pairs(value) do table.insert(keys, key) end
    table.sort(keys, function(a, b)
        local ta, tb = type(a), type(b)
        if ta ~= tb then return ta < tb end
        if ta == "number" or ta == "string" then return a < b end
        return tostring(a) < tostring(b)
    end)
    return keys
end

local function is_array(value)
    local count, highest = 0, 0
    for key in pairs(value) do
        if type(key) ~= "number" or key < 1 or key % 1 ~= 0 then return false, 0 end
        count = count + 1
        if key > highest then highest = key end
    end
    return highest == count, highest
end

local function serialize(value, indent, seen)
    indent = indent or 0
    seen = seen or {}
    local kind = type(value)
    if kind == "nil" then return "nil" end
    if kind == "boolean" or kind == "number" then return tostring(value) end
    if kind == "string" then return string.format("%q", value) end
    if kind ~= "table" then error("unsupported campaign data type: " .. kind) end
    if seen[value] then error("campaign data contains a cycle") end
    if indent > 32 then error("campaign data nesting is too deep") end

    seen[value] = true
    local pad = string.rep("    ", indent)
    local child_pad = string.rep("    ", indent + 1)
    local parts = {"{"}
    local array, length = is_array(value)
    if array then
        for i = 1, length do
            table.insert(parts, "\n" .. child_pad .. serialize(value[i], indent + 1, seen) .. ",")
        end
    else
        for _, key in ipairs(sorted_keys(value)) do
            local encoded_key = "[" .. serialize(key, indent + 1, seen) .. "]"
            local encoded_value = serialize(value[key], indent + 1, seen)
            table.insert(parts, "\n" .. child_pad .. encoded_key .. " = " .. encoded_value .. ",")
        end
    end
    if #parts > 1 then table.insert(parts, "\n" .. pad) end
    table.insert(parts, "}")
    seen[value] = nil
    return table.concat(parts)
end

local function safe_load(path)
    local chunk, load_error = loadfile(path, "t", {})
    if chunk == nil then return nil, load_error end
    local ok, value = pcall(chunk)
    if not ok then return nil, value end
    if type(value) ~= "table" then return nil, "file did not return a table" end
    return value
end

local function atomic_write(path, value)
    local temporary = path .. ".tmp"
    local backup = path .. ".bak"
    local f, open_error = io.open(temporary, "w")
    if f == nil then return false, open_error end

    local ok, encoded = pcall(function()
        return "return " .. serialize(value) .. "\n"
    end)
    if not ok then
        f:close()
        os.remove(temporary)
        return false, encoded
    end

    local write_ok, write_error = pcall(function() f:write(encoded) end)
    f:close()
    if not write_ok then
        os.remove(temporary)
        return false, write_error
    end

    os.remove(backup)
    if file_exists(path) then
        local moved, move_error = os.rename(path, backup)
        if not moved then
            os.remove(temporary)
            return false, move_error
        end
    end

    local installed, install_error = os.rename(temporary, path)
    if not installed then
        if file_exists(backup) then os.rename(backup, path) end
        os.remove(temporary)
        return false, install_error
    end
    return true
end

local function load_with_backup(path)
    local value, err = safe_load(path)
    if value ~= nil then return value end
    local backup = path .. ".bak"
    if file_exists(backup) then
        local recovered, backup_error = safe_load(backup)
        if recovered ~= nil then return recovered, "recovered from backup: " .. tostring(err) end
        return nil, tostring(err) .. "; backup failed: " .. tostring(backup_error)
    end
    return nil, err
end

local function is_integer(value, minimum, maximum)
    return type(value) == "number"
        and value % 1 == 0
        and value >= minimum
        and value <= maximum
end

local function valid_position(value)
    return type(value) == "table"
        and is_integer(value.mapGroup, 0, 255)
        and is_integer(value.mapNumber, 0, 255)
        and is_integer(value.x, 0, 255)
        and is_integer(value.y, 0, 255)
end

local VALID_DIRECTIONS = {Up = true, Down = true, Left = true, Right = true}

local function validate_stage(stage, runnable)
    if type(stage) ~= "table" then return false, "stage must be a table" end
    if type(stage.id) ~= "string" or stage.id == "" then return false, "stage id is missing" end
    if type(stage.name) ~= "string" or stage.name == "" then return false, "stage name is missing" end
    if type(stage.targets) ~= "table" then return false, "stage targets must be a list" end

    local seen = {}
    for _, species_id in ipairs(stage.targets) do
        if not is_integer(species_id, 1, 251) then return false, "target species must be 1-251" end
        if seen[species_id] then return false, "target species are duplicated" end
        seen[species_id] = true
    end
    if runnable and #stage.targets == 0 then return false, "stage has no targets" end

    if stage.anchor ~= nil and not valid_position(stage.anchor) then
        return false, "stage anchor is invalid"
    end
    if runnable and stage.anchor == nil then return false, "stage has no anchor" end

    if stage.routeToNext ~= nil then
        if type(stage.routeToNext) ~= "table" then return false, "route must be a list" end
        for _, step in ipairs(stage.routeToNext) do
            if type(step) ~= "table" or not VALID_DIRECTIONS[step.direction] then
                return false, "route contains an invalid direction"
            end
            if not valid_position(step.from) or not valid_position(step.to) then
                return false, "route contains an invalid checkpoint"
            end
        end
    end
    return true
end

function M.validate_profile(profile, require_runnable)
    if type(profile) ~= "table" then return false, "profile must be a table" end
    if profile.schema ~= SCHEMA_VERSION then return false, "unsupported profile schema" end
    if type(profile.id) ~= "string" or profile.id == "" then return false, "profile id is missing" end
    if type(profile.name) ~= "string" or profile.name == "" then return false, "profile name is missing" end
    if type(profile.stages) ~= "table" then return false, "profile stages must be a list" end
    if require_runnable and #profile.stages == 0 then return false, "profile has no stages" end

    local stage_ids = {}
    for index, stage in ipairs(profile.stages) do
        local valid, err = validate_stage(stage, require_runnable)
        if not valid then return false, string.format("stage %d: %s", index, err) end
        if stage_ids[stage.id] then return false, "stage ids are duplicated" end
        stage_ids[stage.id] = true
        if require_runnable and index < #profile.stages and (stage.routeToNext == nil or #stage.routeToNext == 0) then
            return false, string.format("stage %d has no route to the next stage", index)
        end
    end
    return true
end

function M.new_progress(profile_id)
    return {
        schema = SCHEMA_VERSION,
        profileId = profile_id,
        currentStage = 1,
        completed = {},
        extras = {},
        status = "idle",
        routeStep = 1,
        updatedAt = os.time(),
    }
end

function M.validate_progress(progress, profile)
    if type(progress) ~= "table" then return false, "progress must be a table" end
    if progress.schema ~= SCHEMA_VERSION then return false, "unsupported progress schema" end
    if progress.profileId ~= profile.id then return false, "progress belongs to a different profile" end
    if not is_integer(progress.currentStage, 1, math.max(1, #profile.stages)) then
        return false, "current stage is invalid"
    end
    if type(progress.completed) ~= "table" or type(progress.extras) ~= "table" then
        return false, "progress collections are invalid"
    end
    if not is_integer(progress.routeStep or 1, 1, 1000000) then return false, "route checkpoint is invalid" end
    return true
end

local function slugify(name)
    local slug = tostring(name or ""):lower()
    slug = slug:gsub("[^%w_-]+", "-"):gsub("^-+", ""):gsub("-+$", "")
    if slug == "" then slug = "campaign" end
    return slug:sub(1, 48)
end

local function profile_path(id)
    return base_dir .. "campaign_" .. id .. ".lua"
end

local function progress_path(id)
    return base_dir .. "progress_" .. id .. ".lua"
end

local function load_index()
    local path = base_dir .. INDEX_FILE
    if not file_exists(path) then return {schema = SCHEMA_VERSION, ids = {}} end
    local index, err = load_with_backup(path)
    if index == nil then return nil, err end
    if index.schema ~= SCHEMA_VERSION or type(index.ids) ~= "table" then
        return nil, "campaign index is invalid"
    end
    return index
end

local function save_index(index)
    return atomic_write(base_dir .. INDEX_FILE, index)
end

function M.list_profiles()
    local index, err = load_index()
    if index == nil then return nil, err end
    local profiles, warnings = {}, {}
    for _, id in ipairs(index.ids) do
        local profile, load_error = M.load_profile(id)
        if profile ~= nil then
            table.insert(profiles, profile)
        else
            table.insert(warnings, id .. ": " .. tostring(load_error))
        end
    end
    return profiles, (#warnings > 0) and table.concat(warnings, "; ") or nil
end

function M.load_profile(id)
    if type(id) ~= "string" or not id:match("^[%w_-]+$") then return nil, "invalid profile id" end
    local profile, err = load_with_backup(profile_path(id))
    if profile == nil then return nil, err end
    local valid, validation_error = M.validate_profile(profile, false)
    if not valid then return nil, validation_error end
    return profile, err
end

function M.save_profile(profile)
    local valid, err = M.validate_profile(profile, false)
    if not valid then return false, err end
    profile.updatedAt = os.time()
    return atomic_write(profile_path(profile.id), profile)
end

function M.create_profile(name)
    name = tostring(name or ""):match("^%s*(.-)%s*$")
    if name == "" then return nil, "profile name is required" end
    local index, err = load_index()
    if index == nil then return nil, err end

    local base = slugify(name)
    local id, suffix = base, 2
    local used = {}
    for _, existing in ipairs(index.ids) do used[existing] = true end
    while used[id] do
        id = base .. "-" .. tostring(suffix)
        suffix = suffix + 1
    end

    local profile = {schema = SCHEMA_VERSION, id = id, name = name, stages = {}, createdAt = os.time()}
    local saved, save_error = M.save_profile(profile)
    if not saved then return nil, save_error end
    local progress_saved, progress_error = M.save_progress(M.new_progress(id))
    if not progress_saved then return nil, progress_error end
    table.insert(index.ids, id)
    local indexed, index_error = save_index(index)
    if not indexed then return nil, index_error end
    return profile
end

function M.delete_profile(id)
    local index, err = load_index()
    if index == nil then return false, err end
    local next_ids, found = {}, false
    for _, existing in ipairs(index.ids) do
        if existing == id then found = true else table.insert(next_ids, existing) end
    end
    if not found then return false, "profile does not exist" end
    index.ids = next_ids
    local saved, save_error = save_index(index)
    if not saved then return false, save_error end
    os.remove(profile_path(id))
    os.remove(profile_path(id) .. ".bak")
    os.remove(progress_path(id))
    os.remove(progress_path(id) .. ".bak")
    return true
end

function M.load_progress(profile)
    local path = progress_path(profile.id)
    if not file_exists(path) then return M.new_progress(profile.id) end
    local progress, err = load_with_backup(path)
    if progress == nil then return nil, err end
    local valid, validation_error = M.validate_progress(progress, profile)
    if not valid then return nil, validation_error end
    return progress, err
end

function M.save_progress(progress)
    if type(progress) ~= "table" or type(progress.profileId) ~= "string" then
        return false, "invalid progress"
    end
    progress.updatedAt = os.time()
    return atomic_write(progress_path(progress.profileId), progress)
end

function M.reset_progress(profile)
    local progress = M.new_progress(profile.id)
    local ok, err = M.save_progress(progress)
    if not ok then return nil, err end
    return progress
end

function M.has_progress(progress)
    if progress.currentStage > 1 or progress.status == "completed" then return true end
    for _, stage_values in pairs(progress.completed or {}) do
        if type(stage_values) == "table" and next(stage_values) ~= nil then return true end
    end
    return #(progress.extras or {}) > 0
end

function M.make_stage_id(profile)
    local used = {}
    for _, stage in ipairs(profile.stages) do used[stage.id] = true end
    local index = #profile.stages + 1
    local id = "stage-" .. tostring(index)
    while used[id] do
        index = index + 1
        id = "stage-" .. tostring(index)
    end
    return id
end

M.SCHEMA_VERSION = SCHEMA_VERSION
M._serialize = serialize
M._set_base_dir_for_tests = function(path)
    base_dir = path
    if not base_dir:match("[/\\]$") then base_dir = base_dir .. "/" end
end

return M
